CREATE EXTENSION IF NOT EXISTS pgcrypto; 

DROP TABLE IF EXISTS people;
CREATE TABLE IF NOT EXISTS people (
    id UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    name VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    username TEXT NOT NULL,
    encrypted_password TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(username)
);
